baseurl = "/"
languageCode = "en-us"
theme = "hello-world-cloak"
paginate = 5

[permalinks]
  create-project = "/:year/:month/:title/"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "guides"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Enable to show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "Rubik | An efficient framework for Go"
    subtitle = "Welcome to Rubik Docs"
    keywords = ""
    copyright = "© Ashish Shekar 2020"
    # menuMore = "About"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "rubik"
      logoHomeLink = "/guides/getting-started"
    # or
    #
      path = "/img/icon.png"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "gs"
        name = "Guides"
        url = "/guides"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "api"
        name = "API Docs"
        url = "https://pkg.go.dev/github.com/rubikorg/rubik?tab=doc"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "sc"
        name = "Source Code"
        url = "https://github.com/rubikorg/rubik"
        weight = 3
        target = true

